#+TITLE: Updates from dtospace
#+DESCRIPTION: Updates from dtospace

On my nightstand is a 1929 [[http://en.wikipedia.org/wiki/Epistemology][epistemology]] text called /Mind and the World Order/, by [[http://en.wikipedia.org/wiki/Clarence_Irving_Lewis][Clarence Irving Lewis]]. (Actually I've been firmly
lodged in the 1900-1936 period for quite some time now---whereas for
music it's the 70's.) Oddly enough, I've owned a used copy for some
years now, but never got around to reading it until now.

I know I often write about philosophy books on this blog, as it's a
big hobby for me. But don't anybody get the idea that I'm breezing
through these books. /Mind and the World Order/ is not light reading;
it dives more or less immediately into such issues as (for example)
whether the universe has some special character or structure that
makes it susceptible to interpretation and categorization by the mind,
or if, instead, our shared categories are merely "the combined result
of the similarity of human animals, and of their primal interests, and
the similarities of the experience with which they have to deal." So
I have to carefully read and re-read each paragraph, often several
times, to understand what is being said and follow the long chains of
argument that logicians like Lewis revel in. The only thing I can
compare it to is reading a computer program.

So what have I learned about the structure of the universe now that
I'm 45 pages into the book? Well, Lewis seems to be saying that the
/possibility/ of knowledge does not /require/ us to believe that the
fabric of reality itself is somehow uniquely in tune with the
interpretive apparatus of the mind. (Compare this with Wittgenstein's
[[http://en.wikipedia.org/wiki/Tractatus_Logico-Philosophicus]["The world divides into facts."]])

Lewis is from my own home state of [[http://en.wikipedia.org/wiki/Massachusetts][Massachusetts]], which may be why I
find him a bit easier to read than [[http://en.wikipedia.org/wiki/Wittgenstein][Wittgenstein]]. I can read the latter
only in translation (not to mention his utterly flat and
succinct-as-a-machine-gun writing style.) 

In other news, [[http://emacs-ontology-project.googlecode.com][Eon]] should be in beta by New Year's.
