#+TITLE: Book Review: "Mind and the World Order"
#+DESCRIPTION: Book Review: "Mind and the World Order"

Some years ago I bought a used Dover reprint of Clarence Irving Lewis'
major full-length work, entitled "Mind and the World Order:
Outline of a Theory Of Knowledge". It sat in a box in the garage until
a few weeks ago, when I pulled it out on a whim and decided to read
it.

The scope of Lewis' 1929 treatise extends from the first nerve impacts
of experience to the whole of all reality and the end of time. The
problem of knowledge is the problem of how we can possibly make that
leap from the /given/---the undeniable flat fact of conscious
experience itself in which sense-data such as "red" and "cold" are
presented to our awareness---to "reality". In Lewis' view, we cannot
have knowledge of reality except by conceptual interpretation of the
given. This is because we decide the "reality" of something (an
experience) by making use of our /criteria of reality/ (of various
sorts: physical reality, cognitive reality, mathematical reality). But
since experience includes illusion, hallucination, and error, we
reject something not fitting our criteria as "unreal".  These criteria
are therefore a priori---i.e. not empirical, certain in advance of
experience---for whatever experience does not fit the criteria is
thrown out of court in just this fashion. But these criteria do not
appear out of nowhere; we arrive at them by generalization from past
experience. And so the given nonetheless conditions and shapes the
conceptual scheme we use to interpret it. For example we sense those
tell-tale marks of a dream-experience, and therefore recognize it as
unreal (either by becoming aware of this fact during the dream, or
afterward by waking up in bed.) But we would not even divide our
experience into dreaming and wakefulness without having first had
both. 

So much for my summary of this 400+ page book. What about my review? I
enjoyed this book enormously and would recommend it to anyone
interested in philosophy. I would definitely read it again sometime,
which I can say of very few books. "Mind and the World Order", far
from being forgotten in a box in the garage, will now hold a special
place on my bookshelf.


