#+TITLE: Getting Things Done: Reading a Book!
#+DESCRIPTION: Getting Things Done: Reading a Book!

This post is not about *Getting Things Done(TM)*, but rather about
/doing/ something in particular: reading "Mind and the World Order" by
Clarence Irving Lewis. I mentioned this book on my blog a while back,
when I had only read up through the first chapter. I'm now about
three-quarters finished with the main text, and it's been quite
enjoyable. But this post isn't about the book---it's about /reading/
the book, and how I am Getting it Done.

This is important to me, because I have a lot of trouble /finishing/
books. I'll read a few chapters, but then some other book in the room
will catch my eye, and I'll switch.

Once I realized this, I decided to put "Mind and the World Order" on
my nightstand, and then *removed all other books* from the room. Now
the rest of my books are on another floor of the house; when I am in
my bedroom (where most of my reading work is done) there is nothing
else around to read but the book I'm trying to finish. It's worked out
very well, as I'll be finished with MWO in a few days or so.

