#+TITLE: Some of my game designs

** About me

I am an independent games developer in the U.S. Northeast, and work
primarily in [[http://en.wikipedia.org/wiki/Common_Lisp][Common Lisp]]. Since 2008 I have worked on several projects
for the PC platform. All my games are available for free and are
compatible with Microsoft Windows, Mac OSX, and GNU/Linux. You can
catch the latest news on my [[http://blocky.io/blog/][game development blog]].

And now a bit about each game, with appropriate links:

* Xalcyon

Multi-directional dual analog stick shooter. Work-in-progress. Check
out the [[http://dto.github.com/notebook/xalcyon.html][Xalcyon page]] for more pics, info, and downloads.

| file:../images/Screenshot-12.png |  file:../images/Screenshot-14.png |

* XONG

file:../images/xong.png

XONG is a fast-paced colorful puzzle combat roguelike. Die a million deaths
in this mashup of fragmented 8-bit games.

 - [[http://dto.github.com/notebook/xong.html][Download from the XONG home page]].
 - [[http://playthisthing.com/xong][Play This Thing review]]
 - [[http://www.gamesetwatch.com/2010/02/xong_combines_breakout_snake_a.php][GameSetWatch review]]

* Sanctuary

A post-apocalyptic forest survival roguelike with atmospheric sounds
and music.

file:../images/snow.png
file:../images/tundra.png

 - [[http://dto.github.com/notebook/sanctuary.html][Download from the Sanctuary home page]].

* Other projects

See the [[file:other-projects.org][other projects]] page for various other stuff.
