* Dashboard

** TODO annotate missions with asset/coding todos
** TODO move all cons assets into void/ dir
** TODO get basic nebula map running

* Overview

"Void Mission" is a sci-fi action role playing game
divided into three episodes. The action takes place in a 2-D pixeled
future in which you fly a transforming humanoid/jet suit in both
exterior space and interior environments while firing projectile
and/or energy weapons at enemies and simultaneously avoiding their
fire. The story is largely told through text, represented in the game
as data files, emails, or voice communications with a non-player
character. Gameplay is tied into the story with missions that require
balancing combat with exploration and puzzle solving.

* Gameplay design

** Flow

Gameplay is mission-based, with one mission leading to another in more
or less linear fashion, perhaps with side missions. Each mission is
self contained, and the player and his inventory are all that survive
a mission. Progress is managed using a mission structure (see mission.lisp)

** Presentation

 - 2-D grid based world, with 16x16 pixel objects and characters, with
   additional sprite support for a blend of tile/sprite approaches.
 - 1280x720 widescreen HD
 - use public-domain NASA imagery for textures, plain black for space background
 - try filling the screen with black and creating transparent text controls that go on top
 - rez-like vivid stylized vector graphixxx on top of the hubble stuff

** Player 

The player spends the entire game inside an Olvac mimetic-plasteel
environment suit, and can move freely between interior and exterior
scenes. This suit has two modes: humanoid mode, in which the suit acts
as an exoskeleton for exploring human-scale environments, and a
fighter mode with high-speed jetpack and wide, micro-thin plasteel
wings for extra-vehicular activity and combat.

The suit's energy shield is its sole defense; when SP (shield points)
drop to zero, you die. 

All gameworld interaction is accomplished with the arrow keys, shift,
and the keys Z and X:

  - Arrow keys (or numeric keypad) for player movement.
  - Shift-arrow for activating the selected inventory item.
    If this is a gun for example, you fire in that direction.
  - Z to change the selected inventory item
  - X for picking up items, activating switches, and so on.
  - C to drop the selected inventory item

* Story background

It's 2061. If only there were enough endurium!

It's been known for decades that Humanity's reach within the Milky Way
is limited only by the supply of endurium, its rare and precious
fuel. The energy crises of C.E. 2021 and C.E. 2027-2031 caused global
economic, social, and environmental disruption, and with this
disorganization came the concentration of wealth and power in the
hands of the government and corporate elites.

Early attempts at control and regulation of endurium met with initial
success. The space-faring nations---Russia, China, India, Japan,
Brazil, and the United States---along with the ESA (European Space
Agency), could quite naturally claim endurium for themselves. But
economies of scale and espionage in spaceflight technology eventually
brought smaller deposits and endurium dust streams throughout the
interstellar neighborhood within the reach of multinational
corporations and various non-state actors. The largest of these formed
what they called a "sovereign", open, and successful market in
endurium, spaceflight technology, and various otherwise-controlled
materials. The split between the Spacefaring Nations on the one hand,
and the United Nations on the other, threatens to break into
full-scale interstellar war; as Earth's environment continues to
decay, the demand for endurium has reached a critical point.

A new high-powered telescope operated by Xiomacs Corporation detects a
pattern of gas streamers radiating high in the ultraviolet, within a
cavernous void in galactic space. Subsequent observations show that
the streamers are emitted from a string of black holes. The
scientists, seeing the pattern's obviously artificial nature, guess at
a propulsion method being used to drive a spacecraft, and begin to
look for something at the trail's leading edge. A year later one of
the flare-ups is observed, and the calculations fall into place: the
source of the black holes is an object about as massive as Jupiter,
but much smaller and far more dense. And it has been accelerating for
1.2 billion years by riding on streams of gas being ejected from the
black holes at relativistic speeds. It is given the name DVO1, for
Deep Void Object 1.

* Plot for the "End of Line" story arc

** Episode 1

A mysterious Xiomacs operative named Brennan stays in the Void Rider
as mission commander, while you take off in an Olvac multi-environment
suit. Your mission is to rendezvous with the DVO and make initial
discoveries.

*** 1.1: Take cloud measurements

** TODO Create large nebula image

The cloud obscuring the DVO is meant as a shield to protect it from
the ultraviolet radiation caused by the black holes that propel it
across the universe. Drop scanning devices at each of 3 nav points
surrounding the cloud to complete this mission.

A strange transmission burst is received after the 1st scanning device
is placed. The game's first enemies strike after the 2nd scanning
device is placed.

The measurement data enable plotting a path through the cloud to the
DVO itself.

*** 1.2: Enter DVO orbit

Fight your way through the cloud and enter orbit around the DVO. You
discover a large cruiser already in orbit, a dead hulk with no energy
or life signs. At this point it becomes obvious that you are not the
first human to visit the DVO, and that at least one other Corporation
has reached orbit and possibly the DVO itself.

*** 1.3: Retrieve memory card

You must restore power to the cruiser and retrieve a memory card with
a copy of the map. Once power is restored, security gates will
activate, and you must throw switches to turn them off. Once you get
the memory card, this is combined with new information (ancient texts)
possessed by Xiomacs. This helps Brennan choose an appropriate landing
site on the DVO.

** Episode 2

*** 2.1 Investigate landing site

You find yourself in a windswept ocean of grey sands with outcroppings
of black glass. This more ambient level involves radar searching and
some digging with charges, as well as a climactic boss encounter with
a big sprite :)

You find some supplies and a high-bandwidth transmitter at the
scattered camp sites of the previous expedition's landing.

After defeating this boss you may enter the DVO itself. 

*** 2.2 Investigate DVO origins and purpose

You discover the probe carries the last embryos and the encoded
knowledge of a dying species. The probe is automatically carrying out
its mission to escape a replicating, matter-rearranging mechanical
menace known as the Black Metal. The goal is for the probe to tear a
portion of the universe away from ours at the moment of the Heat
Death, so that the new universe and the old will be absolutely
causally unconnected; only in this way can the Black Metal be escaped,
and their race renewed. 

The Ancients calculated that the Black Metal would grow forever,
dominating matter and space without limit, and therefore all
information and energy. It would be the extinction of all life, and
eventually of all phenomena; a true Heat Death. (The metric expansion
of space and the DVO's great speed ensure that any pursuing Black
Metal objects could never reach the DVO.)

*** 2.3 Return to surface

You receive an urgent message from Brennan but he is cut off in
mid-sentence, something about getting back to the ship. When you reach
the surface, fighting many enemies along the way, the computer decides
to speak, and tells you that you've come 31 million years in the
future, and Brennan (and the rest of Humanity) are long dead.

** Episode 3

*** 3.1 Return to Void Rider

The computer explains that it just awoke, and cannot control its
malfunctioning defense systems (i.e. the enemies you have encountered
up until this point.) Furthermore, the entire mission is in danger,
because a tiny capsule of dormant Black Metal had been secretly
installed aboard the Void Rider, still orbiting the DVO and now slowly
being transformed. In fact the whole mission is a plot to take over
all the DVO's, a plot organized and executed by the Black Metal
itself, who manipulated Xiomacs Corporation through various human
contact personalities. By contaminating the DVOs with Black Metal, the
substance could survive and flourish in the new "tear-away" universes,
and enlarge its dominion to the total range of possible universes; a
dark consciousness that has absorbed literally Everything. The only
way to destroy the Void Rider is to steer it into the path of one of
the black holes as it is ejected from the DVO.

*** 3.2 Reprogram flight computer

Go aboard the Void Rider and reprogram the flight computer so that it
flies into the path of the next black hole. Along the way one must
find two encryption keys to unlock doors. Here one discovers documents
and logs relating to the failed mission and what happened to Brennan
and the Void Rider after you disappeared. You learn that Brennan may
be alive, in stasis somewhere on the DVO. Furthermore the cosmological
speculations of another crew member hint at manifold
possibilities. After Brennan left for the DVO, the remaining crew ran
out of supplies and starved. But before this happened, there were
glimmers of a way back in time; by traveling in a shuttle along the
trail of black holes left by the DVO, one could reverse time and
travel to the point and time of the object's origin.

*** 3.3 Restore engine power

Reactivate the Void Rider's engines so that the flight computer can
steer it into the path of the black hole, and then escape back to the
DVO.

The DVO fires a black hole, and the Void Rider is destroyed
utterly. 

*** 3.4 Investigate stasis chamber 

The computer gets unusual levels of electromagnetic noise in one spot
on the surface; you are led to a stasis chamber where you discover
Brennan frozen in time. After un-freezing he takes the Black Metal
capsule from his pocket and reveals that the Black Capsule contains
sufficient Black Metal to dominate any new universe formed by the DVO,
and that the hive mind has promised long life and vast powers to those
who advance its cause. After a climactic battle with Brennan, the
Black Capsule falls into the player's hands.

*** 3.5 Destroy black capsule

You take the black capsule to the propulsion lab, where it is disposed
of in a black hole before ejection.

The computer explains that in order to travel back to your own epoch,
you need a much longer trail of black holes to accelerate along. The
computer calculates that you'd need to wait many billions of years, so
you enter a stasis chamber and awaken sometime just before the Heat
Death, into a nearly featureless cosmos. The DVO has decayed
significantly and seems barely able to continue its mission. The
computer itself is tired of consciousness.

You enter a stasis chamber and launch yourself back along the trail of
black holes, slingshotting from one event horizon to another, and
arrive in an unknown area.

